[package]
name = "spm_precompiled"
version = "0.1.0"
authors = ["Nicolas Patry <patry.nicolas@protonmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
nom = "5.1"
unicode-segmentation = "1.6"

[dev-dependencies]
serde_json = "1.0"
